name: to_do_list_bloc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  path_provider: ^2.1.5
  hydrated_bloc: ^10.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  get_it: ^8.0.3
  injectable: ^2.5.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.5
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  path: ^1.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.0.3
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15
  drift_dev: ^2.26.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/